### ISSUE TITLE
How should scholar's profile section look like?

### ISSUE THREAD

**Issue by pnijhara** [SSGSA-dev/ssgsa-application-portal#27]
### Discussed in https://github.com/SSGSA-dev/ssgsa-application-portal/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **pnijhara** August 19, 2021</sup>
As suggested by @sanjana-302 we can try "modals". What do you all think?</div>

**Comment by sanjana-302** [comment]
Will find some pre-built designs to portray exact functioning.

**Comment by pnijhara** [comment]
Let's discuss this with Noor.
