### ISSUE TITLE
Discussion: How to write ISRA in the header?

### ISSUE THREAD

**Issue by pnijhara** [SSGSA-dev/ssgsa-application-portal#30]
### Discussed in https://github.com/SSGSA-dev/ssgsa-application-portal/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **pnijhara** August 19, 2021</sup>
Currently, ISRA is written as **International Summer Research Award(ISRA)** in the header. What do you all think? Should we continue with the full form or save the space by writing "ISRA"?</div>

**Comment by sanjana-302** [comment]
It looks fine on a big screen but on an i-pad sized screen, it is not looking apt. We can reduce the size there,
