### ISSUE TITLE
Default page layout

### ISSUE THREAD

**Issue by pnijhara** [SSGSA-dev/ssgsa-application-portal#35]

**Comment by himanshuvarandani** [comment]
@pnijhara Can you provide some description for this.

I am thinking to change "_app.js" file and add header and footer to it instead of all files seperately, i.e. we can make "_app.js" to be default page wrapping the provided component of requested page.

**Comment by pnijhara** [comment]
Yeah, that sounds good. Maybe @roshnet can provide you with a detailed description.

**Comment by himanshuvarandani** [comment]
@pnijhara We have only one structure for now, but what about application portal did we have same structure for that also?
