### ISSUE TITLE
Some UI Suggestions

### ISSUE THREAD

**Issue by ayaankhan98** [SSGSA-dev/ssgsa-application-portal#36]
![1](https://user-images.githubusercontent.com/43348292/131223886-f73f1afb-5d5d-40d0-bf3d-481a63fc8b08.png)

- UI of this section can be improved by using some type of animated stats counter, [see here](https://elfsight.com/number-counter-widget/) (see the below section in the above link)
![2](https://user-images.githubusercontent.com/43348292/131223962-28cee09a-861c-4db2-be0d-e7041884f1b2.png)

- Lower section of homepage looks a bit clutterd, may be little bit of spacing between components can improve UI
![3](https://user-images.githubusercontent.com/43348292/131224036-0a3c5455-1c77-4773-ac0c-69ee24d448fc.png)

**Comment by ayaankhan98** [comment]
- Would be nice to replace certain images with their vector graphics equivalent such as SSGSA logo, Image of MasterCard, VISA etc (in sponsor section) and other related images.

**Comment by pnijhara** [comment]
I agree with your point regarding images. Images are used just for place holding. We will be replacing them with some better quality images or as suggested with their vector graphics equivalent.

If you want you can work on the animated number UI issue. That would be a huge help.
