### ISSUE TITLE
Improvement over animated number counter

### ISSUE THREAD

**Issue by ayaankhan98** [SSGSA-dev/ssgsa-application-portal#39]
Related Issue #36 
Previous PR #37

## Context

A better way to do this is show count animation only when Counter component comes into picture (meaning in viewport). The way it's working right now is it starts as soon as the web page loads, and may be it will not make any sense because it will give static view as earlier if the user does not scrolls to that component in mobile view on load or in desktop mode (if component is out of viewport onload).

## Possible Solution
A simple solution to this is to create a custom hook to check the visibility of a component in view port or may be track the window scroll position and check if your div comes into picture or not (Perhaps there are other better ways to achieve the same).

**Comment by pnijhara** [comment]
Since the counter is placed above the carousel, I think there is no need to set any custom hook for now.
