### ISSUE TITLE
Add Drop Down features in Navbar buttons

### ISSUE THREAD

**Issue by maaz-bin-asad** [SSGSA-dev/ssgsa-application-portal#40]
Add drop-down options for "About", "Apply" and "Alumni" buttons in the navbar. Refer to slides 1 and 2 for details.

**Comment by himanshuvarandani** [comment]
@maaz-bin-asad Is anyone working on this issue?

Can I start working?

**Comment by maaz-bin-asad** [comment]
@himanshuvarandani Assigned! All the best.
