### ISSUE TITLE
Add floating news above first carousel

### ISSUE THREAD

**Issue by maaz-bin-asad** [SSGSA-dev/ssgsa-application-portal#41]
![Screenshot (267)](https://user-images.githubusercontent.com/60134184/134033671-11eb6470-9a5e-4bec-899a-c7192640dbea.png)

**Comment by Ahrazshamim** [comment]
I would like to work on this issue.

**Comment by maaz-bin-asad** [comment]
@Ahrazshamim Assigned. All the best.
