### ISSUE TITLE
Add "Advisory board", "Leadership history" and "Donors and Contributions" components

### ISSUE THREAD

**Issue by maaz-bin-asad** [SSGSA-dev/ssgsa-application-portal#45]
Refer to slides 11 and 12

**Comment by harshtaliwal30** [comment]
Can I work on this issue?

**Comment by pnijhara** [comment]
Go ahead!
Take @himanshuvarandani with you as this section is part of the about page.

**Comment by himanshuvarandani** [comment]
@harshtaliwal30 You can add these component in components/About/About.js file. Ping me if any help required.
