### ISSUE TITLE
Bug in UpperCarousel

### ISSUE THREAD

**Issue by himanshuvarandani** [SSGSA-dev/ssgsa-application-portal#58]
**Describe the bug**
Slides of upper carousel have different heights because of the content size. Smaller slide is not covering the carousel.

**Expected behavior**
Slides of carousel should be of same size with content in center.

**Screenshots**
![image](https://user-images.githubusercontent.com/44665645/135335988-b6baf217-07a8-4986-b513-02e4c1f4af4a.png)

![image](https://user-images.githubusercontent.com/44665645/135335875-c15e6979-3771-4471-af13-39db508ebf4e.png)

**Comment by pnijhara** [comment]
It is obvious to have this kind of view. We cannot fix the card size for every slide. There could be variations in the written part of the card. If we fix the card size, it will bring a lot of empty space for the slides with the less written slides and vice versa.

**Comment by himanshuvarandani** [comment]
If we can't give empty space to slide, then we can align the smaller slide to center.

**Comment by pnijhara** [comment]
That can be done if each slide has a seperate code. However, in our case, we have a single where we are fetching data through a loop.

**Comment by pnijhara** [comment]
@jerrycode06 can throw some light on this matter as he wrote the carousel's code.

**Comment by jerrycode06** [comment]
> 
> 
> If we can't give empty space to slide, then we can align the smaller slide to the center.

We are using separate for each slide and we are fetching carousel data from an arrow with a map function. One thing we can do which is conditional CSS classes in which we define one more property in object for the smaller content and bigger content so we can render CSS class according to that property maybe .

**Comment by himanshuvarandani** [comment]
Yeah i have checked and we can fix height by custom css property.

But which UI will look better?
 - One with fixed height.
 - One with adjustable height and aligbed as center.

**Comment by pnijhara** [comment]
@himanshuvarandani @jerrycode06 any update on this? If there isn't I guess we should close this one.

**Comment by himanshuvarandani** [comment]
Yeah we can close this
